slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: localization
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    scan_topic: /scan
    transform_publish_period: 0.05